force-app/main/default/objects/Rule__c/Rule__c.object-meta.xml
<CustomObject>
    <description>To track and change association Rulebook</description>
    <label>Rule</label>
    <nameField>
        <displayFormat>R-{0000000}</displayFormat>
        <label>Rule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Rule_Detail__c/Rule_Detail__c.object-meta.xml
<CustomObject>
    <label>Rule Detail</label>
    <nameField>
        <displayFormat>RD-{0000000}</displayFormat>
        <label>Rule Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rule_Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Rule_Detail__c/fields/Rule__c.field-meta.xml
<CustomField>
    <fullName>Rule__c</fullName>
    <label>Rule</label>
    <referenceTo>Rule__c</referenceTo>
    <relationshipLabel>Rule_Details</relationshipLabel>
    <relationshipName>Rule_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Rule_Detail__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Proposed</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Rule_Detail__c/fields/Text__c.field-meta.xml
<CustomField>
    <fullName>Text__c</fullName>
    <label>Text</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/RulesPdfcmpController.cls
public class RulesPdfcmpController {
	@AuraEnabled
    public static string RulesPdfupdate(String recordId){
        try {
            PageReference RulesPdf = Page.RulesPdf;
            //excelPage.getParameters().put('cid',contactId);
            Blob pdfBlob = RulesPdf.getContent();
            String base64Pdf = EncodingUtil.base64Encode(pdfBlob);
            
            Rule_Detail__c RulesVar =  [SELECT Id,Status__c, Revised_Date__c,Rule__r.Active__c,Title__c, Text__c FROM Rule_Detail__c WHERE Id =:recordId];
            RulesVar.Status__c = 'Proposed';
            update RulesVar;
            return base64Pdf;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}