force-app/main/default/objects/Rule__c/Rule__c.object-meta.xml
<CustomObject>
    <description>To track and change association Rulebook</description>
    <label>Rule</label>
    <nameField>
        <displayFormat>R-{0000000}</displayFormat>
        <label>Rule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Rule__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Rules</relationshipLabel>
    <relationshipName>Rules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Rule__c/fields/Rule_Name__c.field-meta.xml
<CustomField>
    <fullName>Rule_Name__c</fullName>
    <label>Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rule_Detail__c/Rule_Detail__c.object-meta.xml
<CustomObject>
    <label>Rule Detail</label>
    <nameField>
        <displayFormat>RD-{0000000}</displayFormat>
        <label>Rule Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rule_Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Rule_Detail__c/fields/Rule__c.field-meta.xml
<CustomField>
    <fullName>Rule__c</fullName>
    <label>Rule</label>
    <referenceTo>Rule__c</referenceTo>
    <relationshipLabel>Rule_Details</relationshipLabel>
    <relationshipName>Rule_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Rule_Detail__c/fields/Text__c.field-meta.xml
<CustomField>
    <fullName>Text__c</fullName>
    <label>Text</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Subrule__c/Subrule__c.object-meta.xml
<CustomObject>
    <label>Subrule</label>
    <nameField>
        <displayFormat>SR-{00000000}</displayFormat>
        <label>Subrule</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subrules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subrule__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>2500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Subrule__c/fields/Rule_Detail__c.field-meta.xml
<CustomField>
    <fullName>Rule_Detail__c</fullName>
    <label>Rule Detail</label>
    <referenceTo>Rule_Detail__c</referenceTo>
    <relationshipLabel>Subrules</relationshipLabel>
    <relationshipName>Subrules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/SubRuleHandler_TC.cls
@isTest
public class SubRuleHandler_TC {
    static testMethod void testSubRule(){
        Account testAccount = new Account();
        testAccount.Name = 'ABCDEF';
        Id devRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Association').getRecordTypeId(); 
        testAccount.RecordTypeId = devRecordTypeId;
        testAccount.VMS_Company_Key__c = 1;
        insert testAccount;
        
        Rule__c rule = new Rule__c( Rule_Name__c='RULE-1',Account__c = testAccount.Id);
        insert rule;
        
        Rule_Detail__c rd = new Rule_Detail__c(Rule__c=rule.Id,Text__c='Test Rule Detail',Title__c=rule.Rule_Name__c);
        insert rd;
        List<Subrule__c> srList = new List<Subrule__c>();
        Subrule__c  sr1 = new  Subrule__c(Rule_Detail__c=rd.Id,Description__c='test Subrule__c1');
        Subrule__c  sr2 = new  Subrule__c(Rule_Detail__c=rd.Id,Description__c='test Subrule__c2');
        Subrule__c  sr3 = new  Subrule__c(Rule_Detail__c=rd.Id,Description__c='test Subrule__c3');
        srList.add(sr1);
        srList.add(sr2);
        srList.add(sr3);       
        insert srList;

		delete srList[1];
    }
}