force-app/main/default/objects/Rule__c/Rule__c.object-meta.xml
<CustomObject>
    <description>To track and change association Rulebook</description>
    <label>Rule</label>
    <nameField>
        <displayFormat>R-{0000000}</displayFormat>
        <label>Rule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Rule_Detail__c/Rule_Detail__c.object-meta.xml
<CustomObject>
    <label>Rule Detail</label>
    <nameField>
        <displayFormat>RD-{0000000}</displayFormat>
        <label>Rule Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rule_Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Rule_Detail__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <formula>Rule__r.Order__c</formula>
    <label>Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Rule_Detail__c/fields/Rule__c.field-meta.xml
<CustomField>
    <fullName>Rule__c</fullName>
    <label>Rule</label>
    <referenceTo>Rule__c</referenceTo>
    <relationshipLabel>Rule_Details</relationshipLabel>
    <relationshipName>Rule_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Rule_Detail__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Proposed</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Rule_Detail__c/fields/Text__c.field-meta.xml
<CustomField>
    <fullName>Text__c</fullName>
    <label>Text</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Subrule__c/Subrule__c.object-meta.xml
<CustomObject>
    <label>Subrule</label>
    <nameField>
        <displayFormat>SR-{00000000}</displayFormat>
        <label>Subrule</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subrules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subrule__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>2500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Subrule__c/fields/Rule_Detail__c.field-meta.xml
<CustomField>
    <fullName>Rule_Detail__c</fullName>
    <label>Rule Detail</label>
    <referenceTo>Rule_Detail__c</referenceTo>
    <relationshipLabel>Subrules</relationshipLabel>
    <relationshipName>Subrules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/RulesQuickActionController.cls
public class RulesQuickActionController {
    @AuraEnabled
    public static boolean approveRule(string ruledetailId){
        /*Rule_Detail__c rdtoupdate = [select Id,Status__c, Revised_Date__c,Rule__r.Active__c,Title__c, Text__c from Rule_Detail__c WHERE Id =:ruledetailId];
        rdtoupdate.Status__c = 'Active';
        update rdtoupdate;*/
        
        update new Rule_Detail__c(Id=ruledetailId,Status__c = 'Active');
        return true;
    }
    
    @AuraEnabled
    public static boolean denyRule(string ruledetailId){
        update new Rule_Detail__c(Id=ruledetailId,Status__c = 'Denied');
        return true;
    }

    @AuraEnabled
    public static string cloneRule(string ruledetailId){
        //update new Rule_Detail__c(Id=ruledetailId,Status__c = 'Denied');
        Rule_Detail__c initialRd = [select Id,Title__c, Text__c,Rule__c from Rule_Detail__c WHERE Id =:ruledetailId];
        Rule_Detail__c rd = new Rule_Detail__c(Title__c=initialRd.Title__c,Text__c=initialRd.Text__c,Rule__c=initialRd.Rule__c);
        insert rd;
        List<Subrule__c> srList = new List<Subrule__c>();
        for(Subrule__c sr: [select Description__c, Rule_Detail__c from Subrule__c WHERE Rule_Detail__c=:ruledetailId ORDER BY Order__c]){
            Subrule__c srtoinsert = new Subrule__c(Description__c=sr.Description__c,Rule_Detail__c=rd.Id);
            srList.add(srtoinsert);
        }
        insert srList;
        return rd.Id;
    }
    
}