force-app/main/default/objects/Rule__c/Rule__c.object-meta.xml
<CustomObject>
    <description>To track and change association Rulebook</description>
    <label>Rule</label>
    <nameField>
        <displayFormat>R-{0000000}</displayFormat>
        <label>Rule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Rule__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Rules</relationshipLabel>
    <relationshipName>Rules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Rule__c/fields/Rule_Name__c.field-meta.xml
<CustomField>
    <fullName>Rule_Name__c</fullName>
    <label>Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RuleHandler_TC.cls
@istest
public class RuleHandler_TC {
	static testmethod void Insertaccount()
    {
        Account A1= new account();
        A1.Name = 'bankaccount';
        Insert A1;
        list<Rule__c> Rulelist = new list<Rule__c>();
          Rule__c R1 = new Rule__c();
            R1.Rule_Name__c = 'Bankrule1';
        	R1.Account__c = A1.Id;
         Rule__c R2 = new Rule__c();
            R2.Rule_Name__c = 'Bankrule2';
        	R2.Account__c = A1.Id;
            Rulelist.add(R1);
            Rulelist.add(R2);
        Insert Rulelist;
        
        Delete Rulelist[0];
    }
        
}