force-app/main/default/objects/Rule__c/Rule__c.object-meta.xml
<CustomObject>
    <description>To track and change association Rulebook</description>
    <label>Rule</label>
    <nameField>
        <displayFormat>R-{0000000}</displayFormat>
        <label>Rule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Rule__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Rules</relationshipLabel>
    <relationshipName>Rules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Rule_Detail__c/Rule_Detail__c.object-meta.xml
<CustomObject>
    <label>Rule Detail</label>
    <nameField>
        <displayFormat>RD-{0000000}</displayFormat>
        <label>Rule Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rule_Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Rule_Detail__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <formula>Rule__r.Order__c</formula>
    <label>Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Rule_Detail__c/fields/Rule__c.field-meta.xml
<CustomField>
    <fullName>Rule__c</fullName>
    <label>Rule</label>
    <referenceTo>Rule__c</referenceTo>
    <relationshipLabel>Rule_Details</relationshipLabel>
    <relationshipName>Rule_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Rule_Detail__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Proposed</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Rule_Detail__c/fields/Text__c.field-meta.xml
<CustomField>
    <fullName>Text__c</fullName>
    <label>Text</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Subrule__c/Subrule__c.object-meta.xml
<CustomObject>
    <label>Subrule</label>
    <nameField>
        <displayFormat>SR-{00000000}</displayFormat>
        <label>Subrule</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subrules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subrule__c/fields/Alpha_Order__c.field-meta.xml
<CustomField>
    <fullName>Alpha_Order__c</fullName>
    <label>Alpha Order</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subrule__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>2500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Subrule__c/fields/Rule_Detail__c.field-meta.xml
<CustomField>
    <fullName>Rule_Detail__c</fullName>
    <label>Rule Detail</label>
    <referenceTo>Rule_Detail__c</referenceTo>
    <relationshipLabel>Subrules</relationshipLabel>
    <relationshipName>Subrules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/RulesPdfController.cls
public class RulesPdfController {
    FINAL String rdId='a0c6s000000s6GCAAY';
    FINAL String PROPOSED='Proposed';
    public Boolean isCurrentRule{get;set;}
	public Rule_Detail__c RulesVar { get; set; }
	public List<Subrule__c> subruleVar { get; set; }
	public Rule_Detail__c initialRulesVar { get; set; }
	public List<Subrule__c> initialSubRuleVar { get; set; }
    public RulesPdfController(){
        String rId;
        if(test.isRunningTest()){
            rId = [SELECT Id FROM Rule_Detail__c limit 1].Id;
        }else{
            rId = ApexPages.currentPage().getParameters().get('Id');
        }
           
           RulesVar =  [SELECT Id,Status__c, Revised_Date__c,Rule__r.Active__c,Title__c, Text__c,Order__c FROM Rule_Detail__c WHERE Id =:rId ];
           subruleVar = [SELECT Id,Description__c,Alpha_Order__c FROM Subrule__c WHERE Rule_Detail__c =:rId ORDER BY Order__c];

            List<Rule_Detail__c> initialRulesVarList =  [SELECT Id,Status__c, Revised_Date__c,Rule__r.Active__c,Title__c, Text__c,Order__c FROM Rule_Detail__c WHERE Rule__c =:RulesVar.Rule__c AND Status__c='Active'];
            if(initialRulesVarList.size()>0){
                isCurrentRule = true;
                initialRulesVar = initialRulesVarList[0];
                initialSubRuleVar = [SELECT Id,Description__c,Alpha_Order__c FROM Subrule__c WHERE Rule_Detail__c =:initialRulesVar.Id ORDER BY Order__c ];
            }	
        
    }
    
    @AuraEnabled
    public static string getRulesName(String recordId){
        Rule_Detail__c RulesVar =  [SELECT Id,Rule__r.Account__r.Name,Rule__r.Name,Title__c, Text__c FROM Rule_Detail__c WHERE Id =:recordId];
        return RulesVar.Rule__r.Account__r.Name+' - '+RulesVar.Rule__r.Name;
    } 
    
    @AuraEnabled
    public static string RulesPdfupdate(String recordId){
        try {
            PageReference RulesPdf = Page.RulesPdf;
            RulesPdf.getParameters().put('Id',recordId);           
            
            Rule_Detail__c RulesVar =  [SELECT Id,Status__c, Revised_Date__c,Rule__r.Active__c,Title__c, Text__c FROM Rule_Detail__c WHERE Id =:recordId];
            RulesVar.Status__c = 'Proposed';
            update RulesVar;
            String base64Pdf;
            if(!test.isRunningTest()){
            	Blob pdfBlob = RulesPdf.getContent();
            	base64Pdf = EncodingUtil.base64Encode(pdfBlob);
            }else{
                base64Pdf = 'test';
            }
            return base64Pdf;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}